//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex_9_ContactProjectDBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Numbers
    {
        public int Id { get; set; }
        public string PhoneNumber { get; set; }
        public byte Type { get; set; }
        public int UserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
